GET http://localhost:8080/api/books
Accept: application/json


###

POST http://localhost:8080/api/order?store-id=MUNICH
Content-Type: application/json

[
  {
    "isbn": "978-3442241774",
    "title": "Der Herr der Augenringe Paperback",
    "authors": ["Dschey Ar Tollkühn (Autor)", "Margaret Carroux (Übersetzer)"]
  }
]

###

GET http://localhost:8080/api/books?store-id=MUNICH
Accept: application/json


###

GET http://localhost:8080/api/books/978-3442241774
Accept: application/json


###

DELETE http://localhost:8080/api/books/978-3442241774
Accept: application/json

